repos:
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: /home/vkatke/.pyenv/versions/3.11.4/envs/tango/bin/pytest
      language: system
      types: [python]
      args:
        [
          "--pylint", # Only display messages
        ]