repos:
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      args:
        [
          "--pylint", # Only display messages
        ]